#!/bin/sh
 
CFLAGS=$CFLAGS_OLD
export CFLAGS
unset CFLAGS_OLD
 
LDFLAGS=$LDFLAGS_OLD
export LDFLAGS
unset LDFLAGS_OLD

R_LIBS=$R_LIBS_OLD
export R_LIBS
unset R_LIBS_OLD

LD_LIBRARY_PATH=LD_LIBRARY_PATH_OLD
export LD_LIBRARY_PATH
unset LD_LIBRARY_PATH_OLD
