rule integration_prepare:
    input:
        adata  = lambda wildcards: cfg.get_from_scenario(wildcards.scenario, key="file"),
        script = "scripts/runPP.py"
    output:
        join_path(cfg.get_filename_pattern("prepare", "directory_by_setting"), "adata_pre.{prep}")
    message:
        """
        Preparing adata
        wildcards: {wildcards}
        parameters: {params}
        output: {output}
        """
    params:
        batch_key = lambda wildcards: cfg.get_from_scenario(wildcards.scenario, key="batch_key"),
        hvgs      = lambda wildcards: cfg.get_feature_selection(wildcards.hvg),
        scale     = lambda wildcards: "-s" if wildcards.scaling == "scaled" else "",
        rout      = lambda wildcards: "-r" if wildcards.prep == "RDS" else "",
        seurat    = lambda wildcards: "-l" if wildcards.prep == "RDS" else "",
        cmd       = f"conda run -n {cfg.py_env} python"
    benchmark:
        join_path(cfg.get_filename_pattern("prepare", "directory_by_setting"),
                  "prep_{prep}.benchmark")
    shell:
        """
        {params.cmd} {input.script} -i {input.adata} -o {output} -b {params.batch_key} \
        --hvgs {params.hvgs} {params.scale} {params.rout} {params.seurat}
        """


def get_prep_adata(wildcards):
    """
    get R or python adata file depending on integration method
    """
    if cfg.get_from_method(wildcards.method, "R"):
        prep = "RDS"
    else:
        prep = "h5ad"
    return expand(rules.integration_prepare.output, **wildcards, prep=prep)


def get_celltype_option_for_integration(wildcards):
    if cfg.get_from_method(wildcards.method, "use_celltype"):
        label_key = cfg.get_from_scenario(wildcards.scenario, key="label_key")
        return f"-c {label_key}"
    return ""


# ------------------------------------------------------------------------------
# Python specific integration rule.
# TODO: decorate with some detailed information
# ------------------------------------------------------------------------------
rule integration_run_python:
    input:
        adata  = get_prep_adata,
        pyscript = "scripts/runIntegration.py"
    output:
        cfg.get_filename_pattern("integration", "single", "h5ad")
    message:
        """
        Run {wildcards.method} on {wildcards.scaling} data
        feature selection: {wildcards.hvg}
        dataset: {wildcards.scenario}
        command: {params.cmd}
        hvgs: {params.hvgs}
        cell type option: {params.cell_type}
        """
    params:
        batch_key = lambda wildcards: cfg.get_from_scenario(wildcards.scenario, key="batch_key"),
        cell_type = get_celltype_option_for_integration,
        hvgs      = lambda wildcards, input: cfg.get_hvg(wildcards, input.adata[0]),
        timing    = "-t" if cfg.timing else "",
        cmd       = f"conda run -n {cfg.py_env} python"
    benchmark:
        f'{cfg.get_filename_pattern("integration", "single", "h5ad")}.benchmark'
    shell:
        """
        {params.cmd} {input.pyscript} -i {input.adata} -o {output} \
	      -b {params.batch_key} --method {wildcards.method} {params.hvgs} {params.cell_type} \
	      {params.timing}
        """


# ------------------------------------------------------------------------------
# R specific integration rule.
# TODO: decorate with some detailed information
# ------------------------------------------------------------------------------
rule integration_run_r:
    input:
        adata  = get_prep_adata,
        rscript = "scripts/runMethods.R"
    output:
        cfg.get_filename_pattern("integration", "single", "rds")
    message:
        """
        Run {wildcards.method} on {wildcards.scaling} data
        feature selection: {wildcards.hvg}
        dataset: {wildcards.scenario}
        command: {params.cmd}
        hvgs: {params.hvgs}
        """
    params:
        batch_key = lambda wildcards: cfg.get_from_scenario(wildcards.scenario, key="batch_key"),
        hvgs      = lambda wildcards, input: cfg.get_hvg(wildcards, input.adata[0]),
        cmd       = f"conda run -n {cfg.r_env} Rscript",
        timing    = "-t" if cfg.timing else ""
    benchmark:
        f'{cfg.get_filename_pattern("integration", "single", "rds")}.benchmark'
    shell:
        """
        {params.cmd} {input.rscript} -i {input.adata} -o {output} -b {params.batch_key} \
            --method {wildcards.method} {params.hvgs} {params.timing}
        """


# ------------------------------------------------------------------------------
# Simply converts the RDS files created by the R scripts to h5ad files for
# further processing with the metrics rule
# ------------------------------------------------------------------------------
rule convert_RDS_h5ad:
    input:
        i = cfg.get_filename_pattern("integration", "single", "rds"),
        script = "scripts/runPost.py"
    output:
        cfg.get_filename_pattern("integration", "single", "rds_to_h5ad")
    message:
        """
        Convert integrated data from {wildcards.method} into h5ad
        """
    params:
        cmd = f"conda run -n {cfg.conv_env} python"
    shell:
        """
        if [ {wildcards.method} == "conos" ]
        then
            {params.cmd} {input.script} -i {input.i} -o {output} -c
        else
            {params.cmd} {input.script} -i {input.i} -o {output}
        fi
        """


rule integration:
    input:
        cfg.get_all_file_patterns("integration")
    message: "Integration done"
